# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class IntelliCli < Formula
  desc ""
  homepage ""
  version "0.3.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kj455/intelli-cli/releases/download/v0.3.0/intelli-cli_Darwin_arm64.tar.gz"
      sha256 "9f99c7383acc122f696d77c673e99f8517354473405b343d7d77f8ed2747cfe9"

      def install
        bin.install "intelli-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kj455/intelli-cli/releases/download/v0.3.0/intelli-cli_Darwin_x86_64.tar.gz"
      sha256 "6bd1f3bc4facdd6e67fef0d6fcddde646b8ec59617428aab6939c16e3f2790f7"

      def install
        bin.install "intelli-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kj455/intelli-cli/releases/download/v0.3.0/intelli-cli_Linux_arm64.tar.gz"
      sha256 "cfa1ca38f38627b42be7698502f317533f09725984c9530d65cd03c59cbdc236"

      def install
        bin.install "intelli-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kj455/intelli-cli/releases/download/v0.3.0/intelli-cli_Linux_x86_64.tar.gz"
      sha256 "50216e39294d87667be76e904a2dc35effb55f1364af00f2a2ba0c1172796c58"

      def install
        bin.install "intelli-cli"
      end
    end
  end
end
